"""Pick FashionMNIST test images for the 'Can you beat the CNN?' game and record the Day-1 CNN's real predictions."""
import base64, json, time
import numpy as np, torch, torch.nn as nn
from torchvision import datasets, transforms

from pathlib import Path
ROOT = str(Path(__file__).resolve().parent.parent)   # repo root; run: python Day1_6h_Plan/make_game_data.py
torch.manual_seed(0)
raw_train = datasets.FashionMNIST(root=ROOT + r"\data", train=True, download=False)
pix = raw_train.data.float() / 255.0
MEAN, STD = pix.mean().item(), pix.std().item()
raw_test = datasets.FashionMNIST(root=ROOT + r"\data", train=False, download=False)
X = (raw_test.data.float() / 255.0 - MEAN) / STD
X = X.unsqueeze(1)
Y = raw_test.targets

class SmallCNN(nn.Module):
    def __init__(self, n_classes=10):
        super().__init__()
        self.features = nn.Sequential(nn.Conv2d(1, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                                      nn.Conv2d(32, 64, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2))
        self.classifier = nn.Sequential(nn.Flatten(), nn.Linear(64 * 7 * 7, 128), nn.ReLU(), nn.Dropout(0.3), nn.Linear(128, n_classes))
    def forward(self, x): return self.classifier(self.features(x))

m = SmallCNN(); m.load_state_dict(torch.load(ROOT + r"\Day1_PyTorch_Fundamentals\models\fashion_cnn.pth", map_location="cpu", weights_only=True)); m.eval()
torch.set_num_threads(4)
with torch.no_grad():
    m(X[:256])                                   # warm-up
    t0 = time.perf_counter(); logits = torch.cat([m(X[i:i + 1000]) for i in range(0, 10000, 1000)]); dt = time.perf_counter() - t0
prob = logits.softmax(1); pred = prob.argmax(1)
acc = (pred == Y).float().mean().item()
print(f"full test acc {acc:.4f}, 10,000 images in {dt:.2f} s")

rng = np.random.default_rng(7)
def pick(classes, n_each):
    out = []
    for c, n in zip(classes, n_each):
        idx = np.nonzero(Y.numpy() == c)[0]
        out += rng.choice(idx, n, replace=False).tolist()
    rng.shuffle(out); return out

r1 = pick(range(10), [2] * 10)
hard = [0, 2, 4, 6]
r2 = pick(hard, [4, 4, 3, 4])
def item(i):
    img = raw_test.data[i].numpy().astype(np.uint8)
    return {"px": base64.b64encode(img.tobytes()).decode(), "y": int(Y[i]), "cnn": int(pred[i]), "conf": round(float(prob[i, pred[i]]), 3)}
data = {"classes": raw_test.classes, "acc": round(acc, 4), "secs10k": round(dt, 2),
        "rounds": [[item(i) for i in r1], [item(i) for i in r2]]}
for k, r in enumerate(data["rounds"]):
    print(f"round {k+1}: CNN {sum(d['cnn']==d['y'] for d in r)}/{len(r)}")
# CNN accuracy on the 4 hard classes over the full test set
mask = torch.isin(Y, torch.tensor(hard))
print("CNN acc on T-shirt/Pullover/Coat/Shirt (full test):", round((pred[mask] == Y[mask]).float().mean().item(), 4))
open(ROOT + r"\Day1_6h_Plan\game_data.js", "w", encoding="utf-8").write(
    "// Generated by make_game_data.py: FashionMNIST test images + real predictions of Day1 models/fashion_cnn.pth\nconst GAME=" + json.dumps(data, separators=(",", ":")) + ";\n")
